from flask import Flask

"""
 IT CREATES AN INSTANCE OF THE FLASK CLASS, 
 WHICH WILL BE YOUR WSGI (WEB SERVER GATEWAY INTERFACE) APPLICATION.
 WSGI IS A SPECIFICATION THAT DESCRIBES HOW A WEB SERVER COMMUNICATES WITH WEB APPLICATIONS.
"""
### WSGI APPLICATION
app = Flask(__name__)  # USING WSGI


# DEORATOR. IT TELLS FLASK WHAT URL SHOULD TRIGGER THE FUNCTION THAT FOLLOWS IT.
@app.route("/")
def welcome():
    return "Welcome to this best Flask course.This should be an amazing course"


@app.route("/index")
def index():
    return "Welcome to the index page"


# THIS CHECKS IF THE SCRIPT IS BEING RUN DIRECTLY (AS THE MAIN PROGRAM) OR IMPORTED AS A MODULE IN ANOTHER SCRIPT. EXECUTION WILL START FROM HERE
if __name__ == "__main__":
    # THIS STARTS THE DEVELOPMENT SERVER AND ENABLES DEBUG MODE, WHICH PROVIDES DETAILED ERROR MESSAGES AND AUTOMATIC RELOADING OF THE SERVER WHEN CODE CHANGES ARE DETECTED.
    app.run(debug=True)
